service: nchtr-io
app: nchtr-io
org: tvergho

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  iamManagedPolicies:
    - arn:aws:iam::aws:policy/AWSLambdaFullAccess
    - arn:aws:iam::aws:policy/AmazonS3FullAccess
  environment:
    BUCKET_NAME: ${self:custom.photosBucket}
    JWT_SECRET: nchtrrrr-cw72hfnsa32jnfa

package:
  exclude:
    - node_modules/**
    - uuid/**

functions:
  getUploadUrl:
    handler: getUploadUrl.handler
    events:
      - http:
          path: signedurl
          method: post
          cors: true
    layers:
      - {Ref: UuidLambdaLayer}

layers:
  uuid:
    path: uuid
    compatibleRuntimes:
      - nodejs12.x

custom:
  photosBucket: nchtr-photos-bucket

resources:
 Resources:
   PhotosBucket:
     Type: AWS::S3::Bucket
     Properties:
       BucketName: ${self:custom.photosBucket}
       CorsConfiguration:
        CorsRules:
          -
            AllowedOrigins:
              - '*'
            AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            MaxAge: 3000
